// <auto-generated />
using CodeWithArash.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeWithArash.Migrations
{
    [DbContext(typeof(CodeWithArashContext))]
    [Migration("20250918185935_UpdateProductCateg")]
    partial class UpdateProductCateg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CodeWithArash.Models.BasketItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BasketItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 100m,
                            QuantityInStock = 1
                        },
                        new
                        {
                            Id = 2,
                            Price = 200m,
                            QuantityInStock = 3
                        },
                        new
                        {
                            Id = 3,
                            Price = 300m,
                            QuantityInStock = 5
                        });
                });

            modelBuilder.Entity("CodeWithArash.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "All about ASP .NET Core and C# programming",
                            Name = "ASP .NET Core 9"
                        },
                        new
                        {
                            Id = 2,
                            Description = "All about JavaScript programming",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 3,
                            Description = "All about Python programming",
                            Name = "Python"
                        },
                        new
                        {
                            Id = 4,
                            Description = "All about Machine Learning",
                            Name = "Machine Learning"
                        });
                });

            modelBuilder.Entity("CodeWithArash.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BasketItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasketItemId = 1,
                            Description = "This course is designed to take you from a beginner to an advanced level in ASP .NET Core 9 development. You will learn the fundamentals of ASP .NET Core, including MVC architecture, Razor Pages, Entity Framework Core, and more. By the end of this course, you will have the skills and knowledge to build robust web applications using ASP .NET Core 9.",
                            Name = "ASP .NET Core 9 - Beginner to Advanced"
                        },
                        new
                        {
                            Id = 2,
                            BasketItemId = 2,
                            Description = "This course is a comprehensive guide to JavaScript programming. You will learn the fundamentals of JavaScript, including variables, data types, functions, and control flow. You will also learn advanced topics such as object-oriented programming, asynchronous programming, and working with APIs. By the end of this course, you will have the skills and knowledge to build dynamic web applications using JavaScript.",
                            Name = "JavaScript - The Complete Guide"
                        },
                        new
                        {
                            Id = 3,
                            BasketItemId = 3,
                            Description = "This course is designed to teach you how to use Python for data science and machine learning. You will learn the fundamentals of Python programming, including data structures, functions, and libraries such as NumPy and Pandas. You will also learn how to use machine learning algorithms and techniques to analyze and visualize data. By the end of this course, you will have the skills and knowledge to work with data and build machine learning models using Python.",
                            Name = "Python for Data Science and Machine Learning"
                        });
                });

            modelBuilder.Entity("CodeWithArash.Models.ProductInCategories", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductInCategories");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 4
                        });
                });

            modelBuilder.Entity("CodeWithArash.Models.BasketItem", b =>
                {
                    b.HasOne("CodeWithArash.Models.Product", "Product")
                        .WithOne("BasketItem")
                        .HasForeignKey("CodeWithArash.Models.BasketItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CodeWithArash.Models.ProductInCategories", b =>
                {
                    b.HasOne("CodeWithArash.Models.Category", "Category")
                        .WithMany("ProductInCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeWithArash.Models.Product", "Product")
                        .WithMany("ProductInCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CodeWithArash.Models.Category", b =>
                {
                    b.Navigation("ProductInCategories");
                });

            modelBuilder.Entity("CodeWithArash.Models.Product", b =>
                {
                    b.Navigation("BasketItem");

                    b.Navigation("ProductInCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
