// <auto-generated />
using CodeWithArash.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeWithArash.Migrations
{
    [DbContext(typeof(CodeWithArashContext))]
    [Migration("20250917084745_SeedCategoryData")]
    partial class SeedCategoryData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CodeWithArash.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "All about ASP .NET Core and C# programming",
                            Name = "ASP .NET Core 9"
                        },
                        new
                        {
                            Id = 2,
                            Description = "All about JavaScript programming",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 3,
                            Description = "All about Python programming",
                            Name = "Python"
                        },
                        new
                        {
                            Id = 4,
                            Description = "All about Machine Learning",
                            Name = "Machine Learning"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
